// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Veterinaria6.Models;

public partial class Disponibilidad
{
    public int CodDisponibilidad { get; set; }

    public DateTime Fecha { get; set; }

    public TimeSpan Hora { get; set; }

    public int Ocupada { get; set; }
    [JsonIgnore]
    public virtual ICollection<Atencion> Atencions { get; set; } = new List<Atencion>();
}